### PR TITLE
Re-implement GitHub repo query

### PR DESCRIPTION
**Pull request by sgrove**
Uses OneGraph's code-exporter to generate an api operation doc with variables and named operations, and converts the repo-import component to the new (slightly different) data structure so that it all works now.

I haven't gotten past the "Add repository to your list" button to convert the other two issue queries, but I'm happy to help with those as well (especially if you want to use GitHub issues to store the list of repositories instead of e.g. prisma)!

Also, I saw I hadn't added the netlify preview domain to the allowed CORS origins. This preview should work now!

### CODE REVIEW

**Comment by sgrove** [comment]
I see that there's a problem with `async`, I'll re-export from the code-exporter to try to fix that, then I'll get a preview that actually works 😂

**Comment by sgrove** [comment]
Ok, good to go! Modulo the `createUser` stuff and whatnot, this should work:

https://5d69e3eed36d45000861b352--cranky-tereshkova-1435ae.netlify.com/new

You can sign in (it'll display `loading` afterwards because of the prisma stuff, but you can ignore it), go to "add a new repo", type in the repo url, and it'll pull the data in!

**Comment by sgrove** [comment]
And, last bit for tonight, this is where the magic `user.email` and `user.id` come from - I configured the OneGraph app to use AuthGuardian on every user login and generate a JWT using these rules:

Screenshot 2019-08-30 20 10 21

If you'd like to do this yourself, sign up for a OneGraph account, set the AuthGuardian rules to be the same as in the screenshot, and replace the `APP_ID` in your code. That should be just about everything you need!

**Comment by bdougie** [comment]
@sgrove I have a onegraph account and APP_ID. Is AuthGuardian an addon within there?

**Comment by sgrove** [comment]
@bdougie It is! You can see in the screenshot in the previous comment where it should be.

**Comment by bdougie** [comment]
Testing and working locally as well as the preview. I am going to merge this and start working on removing Graphcool/prisma errors

**Pull request merged**
